version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=saitama
      - POSTGRES_USER=saitama
      - POSTGRES_PASSWORD=saitama123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgressq/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=ROOT
    ports:
      - 5050:80
